# Generated by Django 4.1.3 on 2022-12-08 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pocket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.URLField()),
                ('name', models.TextField(max_length=10)),
                ('link', models.CharField(default='', max_length=200, null=True)),
                ('height', models.CharField(max_length=10)),
                ('weight', models.CharField(max_length=10)),
                ('classify', models.TextField(max_length=10)),
                ('character', models.TextField(max_length=50)),
            ],
            options={
                'verbose_name_plural': '포켓몬',
                'ordering': ('name',),
            },
        ),
    ]
