# Generated by Django 4.1.3 on 2022-12-08 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbook', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pocket',
            name='detail',
        ),
        migrations.RemoveField(
            model_name='pocket',
            name='type',
        ),
        migrations.AddField(
            model_name='pocket',
            name='type1',
            field=models.TextField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='pocket',
            name='type2',
            field=models.TextField(max_length=10, null=True),
        ),
    ]
