# Generated by Django 4.1.3 on 2022-12-08 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pbook', '0003_remove_pocket_type1_remove_pocket_type2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pocket',
            options={'ordering': ('-name',), 'verbose_name_plural': '포켓몬'},
        ),
    ]
